# Generated by Django 5.0.4 on 2024-05-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='departmentadmin',
            name='gender',
            field=models.CharField(default=11, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentadmin',
            name='phone',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturer',
            name='gender',
            field=models.CharField(default=13, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturer',
            name='phone',
            field=models.CharField(default=13, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=16, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=18, max_length=10),
            preserve_default=False,
        ),
    ]
