# Generated by Django 5.0.4 on 2024-04-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='total_score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
