# Generated by Django 5.0.4 on 2024-06-14 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_scoredetail_active_scoredetail_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisscore',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thesisscore',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 24, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thesisscore',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
