# Generated by Django 5.0.4 on 2024-06-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0006_alter_student_thesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentadmin',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='departmentadmin',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
