# Generated by Django 5.0.4 on 2024-06-21 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0007_departmentadmin_address_departmentadmin_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='reviewer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='theses_reviewer', to='theses.lecturer'),
        ),
    ]
